<Project>
  <Import Project="../Directory.Build.props" />

  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'DictaClone.TestTarget'">
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'DictaClone.TestTarget'">
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'DictaClone.TestTarget'">
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
