<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DictaClone.Core/DictaClone.Core.csproj" />
    <ProjectReference Include="../../src/DictaClone.Mac/DictaClone.Mac.csproj" />
  </ItemGroup>
</Project>
